### PR TITLE
2021 finial-project of RICKand-MORTY 

### PR DESCRIPTION
**Pull request by RICKand-MORTY**
this will be a homework of quweikai

### CODE REVIEW

**Comment by MuZhou233** [comment]
Do you really know what is a title for

**Comment by RICKand-MORTY** [comment]
oh sorry

**Review by RICKand-MORTY — COMMENTED** [review]
This is 2021 finial-project of quweikai

**Review by RICKand-MORTY — COMMENTED** [review]
update check-environment.sh

**Review by RICKand-MORTY — COMMENTED** [review]
update

**Comment by RICKand-MORTY** [comment]
change

**Review by RICKand-MORTY — COMMENTED** [review]
update

**Pull request closed without merging**
