### PR TITLE
Homework_d0h0s

### PR DESCRIPTION
**Pull request by d0h0s**
you will see:

1.<README.md>_it contains the summary of all the classes.

2.<SCRIPT>_it contains the codes of the four questions.

3.One MarkDown file and several files of pictures_it contains the answers of the three questions.

in it.

### CODE REVIEW

**Comment by d0h0s** [comment]
@MuZhou233  This is Wang Xianghong(d0h0s)'s pull request.

**Comment by d0h0s** [comment]
@MuZhou233 I deleted your README.md by mistake. And now, it seems to cause a conflict which protect me from merging. Can you help me make a file which is the same to your repository? Looking forward to your early reply. :)

**Comment by MuZhou233** [comment]
It is not a hard work, just revert or restore the change on that file will free you from conflict

**Comment by d0h0s** [comment]
I really don't know why 2021-finalproject/README.md is my conflicting files. I have tried so much times and find that it will be wrong as long as I do something about README.md. It seems not a conflict about content.  Can you give me some advice?T-T @MuZhou233

**Comment by MuZhou233** [comment]
Current situation is that the file is already deleted in our master branch by a new commit. And seems your branch haven't fetch that. In addition, others' PR, especially merged PR, will give you more help.

**Pull request closed without merging**
