### PR TITLE
BlackRu1's 2021-finalproject

### PR DESCRIPTION
**Pull request by BlackRu1**
This is my test text and the exam for the first semester-work.And I pull this request for my basic homework README.md.It seems that I don't need to create label now so I will pull it straight on the Github instead of creating the test first on my Ubuntu.

### CODE REVIEW

**Comment by BlackRu1** [comment]
Please Review it @MuZhou233 , and I need guidance about how to solve such problem "path-check / check (pull_request) Failing after 6s — check " ,so why other's documents don't need to be checked ? I nearly made a mess on my record pull#48, thus I need to find out what deadly question stopped  me, Thank you.

**Comment by MuZhou233** [comment]
On this page https://github.com/gdut-dynamic-x/missing-semester/pull/48/files , scroll down and you will see some binary files placed in a wrong path

**Comment by BlackRu1** [comment]
Oh, I haven't changed the previous document,(Even if it did, it passed the previous inspection) so I think it's wrong with git question markdown ??? and another key problem is that in any case, I can't modify the correct relative path format so that the pictures can be displayed normally in the file. Maybe  I'll try to comment out the additional parts now that I didn't use in the previous file, and then try again. See you later, Thx.

**Comment by BlackRu1** [comment]
Now I have moved my confuse points but nothing worked.

**Comment by BlackRu1** [comment]
@MuZhou233 我还是用中文吧……review以下然后我还是不清楚昨天那个问题到底出在那里（因为英文出了一些歧义），其实我现在的内容是做完的，提出问题改正之后，顺便也Merge一下，谢谢！

**Pull request closed without merging**
